### ISSUE TITLE
EPL-345 Error exporting to Excel the reports "Trial Balance" and "Journal Entries Report"

### ISSUE THREAD

**Issue by Aguilera-Martin** [etendosoftware/etendo_core#16]
https://incidencias.atlassian.net/jira/servicedesk/projects/ESD/queues/custom/153/ESD-75 

**Error's description**

When exporting the "Trial Balance" and "Daily Transactions Report" reports to Excel, an error is displayed in the Openbravo log:

ERROR org.openbravo.erpCommon.ad_reports.ReportGeneralLedgerJournal - Error captured: javax.servlet.ServletException: Font 'Bitstream Vera Sans' is not available to the JVM. See the Javadoc for more details.

**Steps to reproduce the error**

- Open the report.
- Fill in the filters.
- Export to Excel.

**Expected behavior**

An Excel file is downloaded with the report info according to the filters.

**Affected Version**

[KLAUS](https://klaus.futit.cloud/etendo/security/Login)

Etendo 3.0 PR21Q4.1

**Solution Design (optional)**

This issue has already been resolved by Openbravo in [ISSUE-46016](https://issues.openbravo.com/view.php?id=46016): jasperreports library should be updated to the last version.

Merge Request: https://gitlab.com/openbravo/product/openbravo/-/merge_requests/327

**Comment by isaiasb-etendo** [comment]
It was not possible to reproduce the bug, the tests were performed in an Etendo base environment in version 21Q4
