### ISSUE TITLE
EPL-570: Error within stored procedures ad_sequence_next, ad_sequence_doctype, ad_sequence_doc (ORACLE)

### ISSUE THREAD

**Issue by brunoromerosmf** [etendosoftware/etendo_core#163]
This template applies also for the functions ad_sequence_doctype, ad_sequence_doc
# Error's description
There are many errors on stored procedures and triggers in Oracle due to a deprecated stored procedure called AD_SEQUENCE_NEXT(). When this procedure is called, it raises an application error with the message "@DeprecatedAPI@".

# Steps to reproduce the error

1. Begin testing in Etendo environments.
2. Observe errors on stored procedures and triggers that uses this functions.
3. Trace errors back to the AD_SEQUENCE_NEXT() stored procedure.
4. Attempt to call the procedure, which results in an application error with the message "@DeprecatedAPI@" 

# Expected behavior
The stored procedures and triggers should not have errors related to the AD_SEQUENCE_NEXT() stored procedure. When this procedure is called, it should not raise an application error, and the sequences should be generated as expected.

# Affected Version
Etendo 22.2.1

# Solution Design (optional)
To resolve the issue, the deprecated AD_SEQUENCE_NEXT() stored procedure was replaced with the original version, which seems to have resolved the errors. However, it is not clear if this is the correct resolution, and further investigation may be required to determine the best course of action.

**Comment by Matias-Bernal** [comment]
It is not reproduce in a clean environment with a database Oracle v19.3.0. It issue is related with non execution of modulescript during update.database process.
