### ISSUE TITLE
EPL-643: Dataset Importing Fails on Oracle databases

### ISSUE THREAD

**Issue by RubenEtendo** [etendosoftware/etendo_core#186]
# Error's description

Dataset Importing from the ‘Enterprise Module Management’ window fails if the environment is on an Oracle database. The process throws the following error
![1](https://github.com/etendosoftware/etendo_core/assets/108277366/6351561b-ca33-4cdb-8b86-eacbd3edbd40)

This error is thrown from either the `existsOrgModule` and `selectRegister` methods, both from the `UpdateReferenceDataData` java class, when executing the following query:
![2](https://github.com/etendosoftware/etendo_core/assets/108277366/41454ea3-f8cb-4615-b9e4-e705aacaef1e)

This query’s result is then obtained with the following command:
![3](https://github.com/etendosoftware/etendo_core/assets/108277366/e173ffd5-cdd6-415c-9b80-62ae5f5049d1)

The problem here is that this may work for PostgreSQL databases, which are more lenient in the way query results are obtained. But for Oracle databases, the ‘count’ column is trying to be obtained, but in the query its name is ‘COUNT(*)’

# Steps to reproduce the error

1. Install a module that has organization/client datasets in an Etendo environment with Oracle database. E.g.: org.openbravo.module.remittance
2. Log in as F&B Admin
3. Go to ‘Enterprise Module Management’  window and import the remittance dataset
4. The error will be shown

# Expected behavior

The dataset should be correctly imported

# Affected Version

Etendo `22Q4` and `23Q1`

# Solution Design

Rename the ‘COUNT(*)’ column in the query to ‘count’, the following way, in both of its appearances:
![4](https://github.com/etendosoftware/etendo_core/assets/108277366/e9c1798f-4d8a-4dab-b11d-a619ac0e0676)

**Comment by Matias-Bernal** [comment]
We can not reproduce this issue in a clean environment with Oracle 19c, using the reported version of Etendo and the last current confirmed stable version (23.4.0).
