### ISSUE TITLE
EPL-745: Problem when trying to execute dependencies with module com.etendoerp.localization.extensions in windows

### ISSUE THREAD

**Issue by brunoromerosmf** [etendosoftware/etendo_core#190]
*Error's description*
When I run the command "./gradlew dependencies" on a base etendo in windows, I encounter an error in the handling of this module defined as "JARS". The problem lies in the fact that Gradle is erroneously treating a JAR repository as a ZIP file.
![image](https://github.com/etendosoftware/etendo_core/assets/122372040/93c49a49-579a-4133-847d-093db2db5fc3)
![image](https://github.com/etendosoftware/etendo_core/assets/122372040/387209fc-a09d-4db7-984f-b97ceed25719)

*Steps to reproduce the error*
1) In a base etendo in windows, modify the build.gradle file as shown in the attachment above.

2) Execute the command ./gradlew dependencies

*Expected behavior*
It should handle the repository as a JARS file.

*Affected Version*
22.4.5

**Comment by valeg-etendo** [comment]
This issue was resolved in the following Pull Request: https://github.com/etendosoftware/com.etendoerp.gradleplugin/pull/5
