### ISSUE TITLE
EPL-1014: Issues with Etendo in JAR Format from Version 23.2.5 to 23.3.0

### ISSUE THREAD

**Issue by brunoromerosmf** [etendosoftware/etendo_core#231]
**Error's description**

Starting from version 23.2.5 up to the current version 23.3.0, it is not possible to use Etendo in JAR format. This results in various issues when attempting to run Etendo in this configuration.

**Steps to reproduce the error**

To reproduce the problems, follow these steps:

With Etendo Platform:

Set up the environment using any version within the range [23.2.5, 23.3.0] in JAR format.

Use plugin version 1.1.2 (note that version 1.1.3 is known not to work with JAR).

Execute an 'install' operation.

If you already have a database, run 'update.database'.

With Etendo Base:

Set up the environment using any version within the range [23.2.5, 23.3.0] in JAR format.

Use plugin version 1.1.2 (1.1.3 is known not to work with JAR).

Execute an 'install' operation.

If you already have a database, run 'update.database'.

In any of the above cases, the install error is detailed in the [error-install.md](http://error-install.md/) file and the update.database error is detailed in the [error-update.md](http://error-update.md/) file.

**Expected behavior**

The expected behavior is that Etendo should work without any issues when using versions within the specified range and the specified plugin version in JAR format. However, the described errors and issues are encountered, preventing proper functionality.

**Affected Version**

This issue affects versions from 23.2.5 to 23.3.0 of Etendo when used in JAR format with plugin version 1.1.2.

**Comment by valeg-etendo** [comment]
Same Issue to https://github.com/etendosoftware/etendo_core/issues/221
