### ISSUE TITLE
EPL-1124: Problem when creating a template with a name starting different from "com.etendoerp".

### ISSUE THREAD

**Issue by brunoromerosmf** [etendosoftware/etendo_core#256]
# Error's description
When creating a template with a name that does not start with "com.etendo.erp", when running an export.config.script to create the folder and bring the information of the same to the sources (should be in development), this task brings "extra" lines in the "configScript.xml" file in new module (template).
Attached screenshot of the file:
![image](https://github.com/etendosoftware/etendo_core/assets/122372040/0ce65193-3dea-4eb8-b9e6-c5c6be6d7ba3)

Example of how it should be done correctly:
![image](https://github.com/etendosoftware/etendo_core/assets/122372040/78965e18-d1ea-40eb-918c-076bcbabf85e)

# Steps to reproduce the error
1. Create a simple template, where the name is "example.test".
2. Check “in development“
3. Run ./gradlew export.config.script
4. check the configScript.xml

# Affected Version
  23Q3

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.1.21](https://github.com/etendosoftware/etendo_core/releases/tag/24.1.2).
