### ISSUE TITLE
EPL-1150: Modulescripts execution is skipped when doing update.database in windows

### ISSUE THREAD

**Issue by brunoromerosmf** [etendosoftware/etendo_core#266]
# Error's description
In windows, when running the` ./gradlew update.database` task, it is observed that the modulescripts are not executed.
However, the task concludes with a BUILD SUCCESSFUL.
The following line is showed in the log:
`[ant:java] 40497 [main] INFO  org.openbravo.ddlutils.task.AlterDatabaseDataAll - Skipping modulescripts...`

**Additional information**:
The following line has also been found (at the beginning of this task):
```
[ant:java] 2418  [main] INFO  org.openbravo.ddlutils.task.AlterDatabaseDataAll - Database connection:
jdbc:postgresql://localhost:5432/etendo. User: tad. System User: null
```
The System User variable shouldn't be "null".

# Steps to reproduce the error
It is possible to reproduce this error with the following context:
. Operating system: Windows 11
.Java: 11
.PostgreSQL: 14
.Core: 23.3.4 

  1. Install a clean etendo base environment using the attached build.gradle.
  2. Execute the `./gradlew update.database --info` task.
  3. The skipping modulescripts line appears in the log.
  
# Expected behavior
It is expected that when running the `./gradlew update.database --info task`, the modulescripts should be executed correctly. The task should finish without errors and display "BUILD SUCCESSFUL".
![Captura de pantalla 2023-12-06 150348](https://github.com/etendosoftware/etendo_core/assets/122372040/3d5ffa7d-68bd-4487-a6bb-36d63348f4d6)
Also, in the line mentioned in the additional information, the systemuser should be "postgres".
something like this:
`[ant:java] 2418  [main] INFO  org.openbravo.ddlutils.task.AlterDatabaseDataAll - Database connection: jdbc:postgresql://localhost:5432/etendo. User: tad. System User: postgres`

**Comment by Matias-Bernal** [comment]
We can not reproduce this issue in a clean environment with Oracle 19c, using the reported version of Etendo and the last current confirmed stable version (23.4.0).
