### ISSUE TITLE
EPL-530: Sales Order - When double clicking on the header some fields are modified

### ISSUE THREAD

**Issue by juanfunes1996** [etendosoftware/etendo_core#270]
# Error's description

When entering a record in form mode, from time to time the edit mode of the window is activated without any field having been modified to activate it, and sometimes, the callout associated with the field (business partner) that activated the edit mode is executed causing other fields to change their value.

# Steps to reproduce the error

### Case 1

1. Simulate browser slowness is done in the browser console. Go to the Network section and change the property from "No throttling" to "Slow 3G".
![image](https://github.com/etendosoftware/etendo_core/assets/143511686/ebcc2926-a590-4f5d-bd6a-d7ceb0608ddd)
2. In the sales order window create a new record in form mode.

3. The mandatory fields must be completed. In the payment terms field select a value different than the one the customer has configured as a default value in the Business partner.  Save and close the form mode.

4. Access the record by double clicking on any field of the grid.

5. Open and close the form mode until the edit mode is activated. Sometimes several attempts until it succeeds.

6. Take a look at the video and notice that in one of the attempts the edit mode is activated and the payment terms field is updated to the one the customer has configured by default.

### Case 2

1. Simulate browser slowness is done in the browser console. Go to the Network section and change the property from "No throttling" to "Slow 3G".
![image](https://github.com/etendosoftware/etendo_core/assets/143511686/0ebab8a2-ea20-4b75-b675-84f111b08900)
2. In the sales order window create a new record in form mode.
3. Select a business partner, the tests have been carried out with the business partner Full Moon Restaurants, S.A.
4. Save the record and press the refresh button 2 times. This would cause the edit mode to be activated and in some cases changing the value of the pricelist field as in the attached video. 

TESTED VERSIONS:  22.2.0 |  23.2.0 | 23.3.4

# Expected behavior

When opening in form mode it should never activate the edit mode without clicking on any field or when press the refresh button.

# Affected Version

Any, with or without bundles

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.1.8](https://github.com/etendosoftware/etendo_core/releases/tag/24.1.8)
