### ISSUE TITLE
ETP-44: The error message in the process of "creating invoices from orders" is incorrect.

### ISSUE THREAD

**Issue by brunoromerosmf** [etendosoftware/etendo_core#277]
# Error's description

It is necessary for a business partner to have at least one location assigned with the 'invoicing Address' check enabled. In situations where this is not met, and an attempt is made to create an order from a goods shipment, the 'Invoice Address' field is not completed automatically and is read-only. Subsequently, when trying to generate an invoice from this order (in the "create invoices from orders" window), the system displays an incorrect error message (see attach).

![image](https://github.com/etendosoftware/etendo_core/assets/122372040/034fe077-79d3-447a-acc9-368f965cbe50)

# Steps to reproduce error

1. Have a business partner that does not have any localization with the check marked "invoicing address".
2. Create a “sales quotation“ of this business partner and booked.
3. Create “sales order“ from quotation.
4. Create a "goods shipments" of this business partner from the sales order created.
5. Go to windows “create invoice from orders“ select this order and process.

# Expected Behavior

The error message should specifically indicate that the business partner does not have an assigned 'invoincing Address', which prevents the order from having an associated invoice address.

# Affected version

23.4.0

# Solution Design

1. Modify the order creation process:
   - Retrieve the Business Partner associated with the order.
   - Fetch the invoice address directly from the Business Partner, ignoring any address that might be in the Quotation.
   - Verify if the Business Partner has a valid invoice address.

2. Implement validation logic:
   - If the Business Partner has a billing address:
     - Assign this address to the order.
   - If it doesn't have a billing address:
     - Throw a specific error.
     - Prevent the order creation.

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.2.7][(https://github.com/etendosoftware/com.etendoerp.platform.extensions/releases/tag/2.0.1](https://github.com/etendosoftware/etendo_core/releases/tag/24.2.7)) ⚡ 🚀
