### ISSUE TITLE
EPL-1194: Double Discount Application in the 'Discount' Field in Sales Orders.

### ISSUE THREAD

**Issue by juanfunes1996** [etendosoftware/etendo_core#280]
# Error's description

The discount reported on the sales order line is incorrect when it has decimals, it is rounded to the units.

Steps to reproduce the error

   1.Creation of promotion TESTMS02 for a 15% discount on the item "Still water 1L."
![image](https://github.com/etendosoftware/etendo_core/assets/143511686/919a1fe2-d1f7-41ca-9104-5a2444d4602d)

  2.Creation of sales order 1000412 TESTMS04. In the "Basic discount" tab, a 10% discount from the customer profile 
  appears, which is correct.
![image](https://github.com/etendosoftware/etendo_core/assets/143511686/c976f335-35f0-4fcc-bbfb-cc38580f04d0)

  3.Creation of a sales order line with one unit of "Still water 1L." Upon creating the line, even before saving it, Etendo fills the 
  "discount" box with "15" (15% from promotion TESTMS01) and calculates a net price of 1.30 [1.53*(1-0.15)=1.3005]. This   
  seems to be an error; the "Discount" box should still display "0" (as per the previous functionality prior to the "correction":  ).
![image](https://github.com/etendosoftware/etendo_core/assets/143511686/06b13e58-2843-4b29-b1a5-7a9424b75944)

  4. Upon finalizing the order ("Book"), Etendo calculates an incorrect net price of 1.11. This price seems to correspond to a 
 double cascading application of the 15% promotion TESTMS02 [1.53*(1-0.15)(1-0.15)=1.105425]. The expected net price 
 should be 1.17045 (application of the 10% "Basic discount" followed by the 15% promotion [1.53(1-0.10)*(1- 
  0.15)=1.17045]).
![image](https://github.com/etendosoftware/etendo_core/assets/143511686/fb478b07-717d-410e-92fa-ef93f66791f5)

The double application of the 15% promotion could stem from Etendo applying successively upon finalizing the order ("Book"):

The 15% found in the "Discounts" box, where there should be "0".

The 15% from the promotion configured in "Discounts and promotions".

It does not apply the 10% from the "Basic discount" from the customer profile.

# Expected behavior

Regeneration of changes made and that the behavior of discounts is replicated by OB.

# Affected Version

23.4.1

# Solution Design (optional)

Callouts 

src/org/openbravo/erpCommon/ad_callouts/SL_Order_Amt.java

src/org/openbravo/erpCommon/ad_callouts/SL_Order_Product.java

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [23.4.4](https://github.com/etendosoftware/etendo_core/releases/tag/23.4.4).
