### ISSUE TITLE
EPL-1207: Inefficient handling of processing state when encountering an error and attempting to retry the process. Using Oracle

### ISSUE THREAD

**Issue by juanfunes1996** [etendosoftware/etendo_core#286]
### **Error's description**

Inefficient handling of processing state when encountering an error and attempting to retry the process. Using Oracle

### **Steps to reproduce the error**

Using a Clean Etendo with Oracle

1 - Create an invoice with a closed period date

2 - Try to complete it

3 - Open this period

4 - Complete the invoice
![image](https://github.com/etendosoftware/etendo_core/assets/143511686/ae47b996-10d1-40ff-98aa-fb9b8b840cff)

It should be clarified that this status handling does not occur when using Postgres.

### **Expected behavior**

To be able to process an invoice if everything is in the correct state, even if an error occurred previously, such as a closed period."

### **Affected Version**

23.4.0

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [23.4.4](https://github.com/etendosoftware/etendo_core/releases/tag/23.4.4).
