### ISSUE TITLE
ETP-46: It is possible to modify a Core process definition without having a template under development.

### ISSUE THREAD

**Issue by brunoromerosmf** [etendosoftware/etendo_core#291]
# Error's description

It is possible to modify a Core process definition without having a template under development.

# Steps to reproduce the error

1. No module must be in development
2. Go to the process definition tab and look for the Valued Stock Report record. (for example)
3. Change the Handler field
4. The change will be saved and the module field will no longer have the 2 asterisks.

# Expected behavior

It should come out that the change cannot be saved because the module is not in development.

# Affected Version

Core 23.4.0

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.3.2](https://github.com/etendosoftware/etendo_core/releases/tag/24.3.2) ⚡ 🚀
