### ISSUE TITLE
ETP-47: Invoice line selector does not show records in landed cost tab of good receipts window

### ISSUE THREAD

**Issue by juanfunes1996** [etendosoftware/etendo_core#305]
### **Error's description**

Invoice line selector does not show records in the landed cost tab of goods receipt, but in the cost tab of the Landed cost window it does. They are the same table in both tabs.

### **Steps to reproduce the error**

Creates a landed type in the landed cost type window 
![image](https://github.com/etendosoftware/etendo_core/assets/143511686/d4fb047b-17c3-4f47-8e89-02af541a5165)

Create a purchase invoice with a line that has the product you assigned to the type of landed created above 
![image](https://github.com/etendosoftware/etendo_core/assets/143511686/446860a2-e1b3-45f0-b651-fc0c0a93236d)

Create a good receipt header and create a record in the landed cost tab, when trying to select an invoice line, no records appear.
![image](https://github.com/etendosoftware/etendo_core/assets/143511686/ac597e90-db26-4850-83e0-52dcdbab2e38)

But if you go to the "Landed cost" window, create a record and then create a record in the cost tab, with the type of landed created in the first item, in the line selector appears the line of the invoice created in the second item (example attached to the second image)

### **Expected behavior**

Invoice line selector show records in the landed cost tab of goods receipt and in the cost tab of the Landed cost window 

### **Affected Version**

CORE 23.4.0

### **Solution Design (optional)**

In the selector query it uses two auxiliary inputs:

LCC_Product_ID

LCC_Account_ID

These are only defined for the Cost tab in Landed Cost window.

Replicate these auxiliary inputs for the Landed cost tab of good receipt window.

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.2.8](https://github.com/etendosoftware/etendo_core/releases/tag/24.2.8) ⚡ 🚀
