### ISSUE TITLE
EPL-1238 : No custom accounting can be added to internal consumption

### ISSUE THREAD

**Issue by brunoromerosmf** [etendosoftware/etendo_core#306]
# Error's description

If you want to use custom accounting for the internal consumption table, the process always posts using the Core method, not the custom one.

# Steps to reproduce the error

**Note**: To reproduce the bug, the Accounting Template field in the Active Tables tab of the General Ledger Accounting window must be visible.

1. Create in Accounting Templates a record for the table m_internal_consumption with the Java class that has the accounting customization
for example:
```
package org.openbravo.erpCommon.ad_forms;

import java.sql.Connection;
import javax.servlet.ServletException;
import org.openbravo.base.secureApp.VariablesSecureApp;
import org.openbravo.database.ConnectionProvider;

public class DocInternalConsumptionAccounting extends DocInternalConsumptionTemplate {
    @Override
    public Fact createFact(DocInternalConsumption docInternalConsumption, AcctSchema as, ConnectionProvider conn,
                           Connection con, VariablesSecureApp vars) throws ServletException {
        int aux = 9;
        return null;
    }
}
```
2. In the General Ledger Configuration window, in the Active tables tab, select the record that has the table MaterialMgmtInternalConsumption and in the accounting template field choose the template we just created.
3. Create the Java class that will be the template (it must extend the DocInternalConsumptionTemplate class).
4. Post an internal Consumption
5. The process posts using the etendo process and does not use the template.

# Expected behavior

The process should post using the java class we created.

# Affected version

23.2.4

# Solution design

In the class org.openbravo.erpCommon.ad_forms.DocInternalConsumption there is a method called createFact that has an else like the one in the attached image. (screen1)
The else should be changed by an if like the one in the other attached image (screen2)

![image](https://github.com/etendosoftware/etendo_core/assets/122372040/773a4dac-1855-4aa7-ab03-3bc12670c0e5)
![image](https://github.com/etendosoftware/etendo_core/assets/122372040/a38d8415-9ff7-45b7-8210-946beda27e89)

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.1.7](https://github.com/etendosoftware/etendo_core/releases/tag/24.1.7).
