### ISSUE TITLE
EPL-1275: Loss of bom parent id when sorting to create delivery note lines in customer invoice

### ISSUE THREAD

**Issue by juanfunes1996** [etendosoftware/etendo_core#310]
# Error's description

Loss of bom parent id when sorting to create delivery note lines in customer invoice

Bom_parent_id corresponds to products that have the BOM check =Y checked, which makes the BOM tab visible to specify their composition. It is used in what is called simple production, to make Production Orders with materials only.

https://github.com/etendosoftware/etendo_core/assets/143511686/d73a4971-7c41-4906-9cfd-fc1d67af2af1

# Steps to reproduce the error
1 - Create/modify a product with the "Bill of Materials" checkbox checked (IsBOM). It should have on its "Bill of Materials" tab two products (the quantities of each are not relevant).
![image](https://github.com/etendosoftware/etendo_core/assets/143511686/138b78bc-45ec-4a79-ad7c-55021095e2d7)

2 - Create a sales order. In its lines, manually create one with the previously created/modified product. Then create the same number of lines as the quantity of products that belong to the bill of materials. Each of these products should point to the main product (and the created order number) in its BOM_Parent_id column (if easier, you can show the column which is by default hidden).

3 - Complete the sales order.

4 - In the Good Shipmetn window: Create a header with the same customer and "create lines from" choosing the previously created order and its lines.

5 - Complete Good Shipmetn .

6 - Repeat these steps 3 or 4 times.

7 - In the invoice (client) window: Create a header with the same customer and "create lines from delivery note" choosing the created delivery notes.

8 - Select the delivery notes with their lines and sort as demonstrated in the video.

https://github.com/etendosoftware/etendo_core/assets/143511686/91ff2a8e-7a07-43fc-8240-d58ec4da05ab

![image](https://github.com/etendosoftware/etendo_core/assets/143511686/0922a1ab-4cc6-4ac2-bfec-d746b21aa3b0)

# Expected behavior

Retention of bom parent id when sorting to create delivery note lines in customer invoice.

# Affected Version

Core: 23.4.1

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [23.4.4](https://github.com/etendosoftware/etendo_core/releases/tag/23.4.4).
