### ISSUE TITLE
EPL-1320: Trigger errors are not displayed when creating a new collection from a transaction

### ISSUE THREAD

**Issue by juanfunes1996** [etendosoftware/etendo_core#314]
# Error's description

Trigger errors are not displayed when creating a new collection from a transaction

# Steps to reproduce the error

1 - Add a trigger to the fin_payment table that throws an error of the type RAISE EXCEPTION '%', '@20501@'; --OBTG:-20000-- . Attached example.

```
-- FUNCTION: public.check_fin_payment_trigger()

-- DROP FUNCTION IF EXISTS public.check_fin_payment_trigger();

CREATE OR REPLACE FUNCTION public.check_fin_payment_trigger()
    RETURNS trigger
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE NOT LEAKPROOF
AS $BODY$
BEGIN
    RAISE EXCEPTION '%', '@20501@'; --OBTG:-20000--
END;
$BODY$;

ALTER FUNCTION public.check_fin_payment_trigger()
    OWNER TO tad;


```

2 - In the financial account window, under the transactions tab, create a new record.

3 - Utilize the functionality to add a new payment from this record.

4 - Upon accepting the new payment, the window remains indefinitely loading.

https://github.com/etendosoftware/etendo_core/assets/143511686/e364b0b2-9d14-497a-98a4-e6237a776584

# Expected behavior

Ensure that the process reaches its end by adding the payment, or if a trigger error occurs, display it.

# Affected Version

CORE 23.4.1

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.1.8](https://github.com/etendosoftware/etendo_core/releases/tag/24.1.8)
