### ISSUE TITLE
EPL-1335: In "purchase invoice dimensional report", in Mozilla Firefox, it is not possible to download the report in excel format.

### ISSUE THREAD

**Issue by brunoromerosmf** [etendosoftware/etendo_core#319]
# Error's description

When users accessing Etendo from Mozilla Firefox try to download the report in Excel format, independently of the parameters, the process does not download any file. This inconvenience is not observed when choosing the other formats (html and pdf) where the functionality is executed correctly and the reports are generated and downloaded without problems.

# Steps to reproduce the error

Note: It is worth clarifying that the problem to be reproduced must be in Mozilla Firefox.

1) Go to the window "purchase invoice dimensional report".
2) Fill in the mandatory parameters. You can easily add any information as long as it is consistent.
3) Try to download the report in excel format with the button "Excel format".
4) In addition, try the other formats and you will see that they work.

# Expected behavior
It should download correctly as it happens in Google Chrome

# Affected Version
Etendo 23.4.2

**Comment by facumoyanosmf** [comment]
> [!IMPORTANT]
> Bug resolved in version [23.4.5](https://github.com/etendosoftware/etendo_core/releases/tag/23.4.5).
