### ISSUE TITLE
EPL-1336: Null Session Error in AddPaymentActionHandler

### ISSUE THREAD

**Issue by brunoromerosmf** [etendosoftware/etendo_core#322]
# Error's description
When a settlement payment is made where both invoices have the same amount and the payment is 0, an error message is returned suggesting that this process can be performed in the Business Partner Settlement window. However, the underlying problem is not limited exclusively to this functionality or the Business Partner Settlement module. At the core of the problem is an error in session management within the code, specifically in the AddPaymentActionHandler class.

At line 160 of this file, the line SessionHandler.getInstance().rollback(); returns the message "Session is null," indicating a session management failure that should not occur. This problem extends beyond the specific context of payment settlement, potentially affecting any operation related to the Payment class (FIN_Payment).

Currently, the Business Partner Settlement module is the only one that implements hooks related to the FIN_Payment table, but the error in session management is a core system issue that could affect any future or existing module that implements similar hooks for the Payment class.

# Steps to Reproduce the Error
1. Navigate to the Sales Invoice window.
2. Create a record with a Business Partner that is both a customer and a vendor.
3. Add a line with a product with a net unit price of 100.
4. Click "Complete."
5. Navigate to the Purchase Invoice window.
6. Create a record with the same Business Partner used in the Sales invoice.
7. Add a line with a product with a net unit price of 100.
8. Click "Complete."
9. Navigate to the Payment In window.
10. Make a payment with an amount of 0, select the same Business partner used in both invoices, and press "Add Details."
11. In "Order/Invoice," select the sales invoice and set the amount to 100.
12. In "Invoice for compensation," select the purchase invoice and set the amount to 100.
13. Process the payment.

# Affected Version
Etendo Core 23.4.2

# Other Test Cases

Given: An Etendo Core with the Business Partner Settlement module installed.

When: Perform a settlement payment where the amount of both invoices is the same, and the payment is 0.

Then: The AddPaymentActionHandler should not return "Session is null."

**Comment by RomanMagnoli** [comment]
This case is no longer replicable due to this functionality is not allowed since the fox of task: (https://etendoproject.atlassian.net/browse/EE-758)
