### ISSUE TITLE
EPL-534: 'Post/Unpost' process works incorrectly on 'Internal consumption' window

### ISSUE THREAD

**Issue by juanfunes1996** [etendosoftware/etendo_core#326]
# Error's description

The post/unpost process does not check if an internal consumption’s period is closed when unposting. Posting works OK, the problem is with the unposting.

This error is not reproducible in Openbravo, at least as of their [3.0PR24Q1](https://livebuilds.openbravo.com/context/erp_mp_3.0PR24Q1) core release

# Steps to reproduce the error

Precondition: have the Internal Consumption Window available for accounting

Go to ‘Internal Consumption’ window

Create a new record:Organization: F&B España, S.AMovement Date: 24-01-2023Name: Test

Add lines:Product: Agua sin Gas 1LMovement Quantity: 10Storage Bin: RS-0-0-0

Save

Click on ‘Process internal consumption' button and click OK

Click on ‘Post’ button and click Done

Go to ‘Open/Close period control’ window

Close the Jan-23 period of the ‘Calendario España’ calendar, in the year 2023

Go back to ‘Internal Consumption’ window and select the previously created record

Click on ‘Unpost’ button and click Done

The process will finish successfully

# Expected behavior

the process should not finish successfully, and display a message explaining that the unposting could not be completed due to the closed period

# Affected Version

Etendo 24.1.0

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.1.1](https://github.com/etendosoftware/etendo_core/releases/tag/24.1.1).
