### ISSUE TITLE
ETP-49: Incorrect error return processing in payment. When posting a payment in it gives an incorrect error if the configurations are not correct and there are 2 general ledger

### ISSUE THREAD

**Issue by juanfunes1996** [etendosoftware/etendo_core#334]
# Error's description

Incorrect error return processing in payment. When posting a payment in it gives an incorrect error if the configurations are not correct and there are 2 general ledger. If a payment method has in the "Upon Receipt Use" field a reference to an empty field in the financial account settings, when posting a payment in, it says document disabled error, which is not correct.

# Steps to reproduce the error

1. Create a payment from a registered sales order.
2. The financial account related to the payment, in the payment method related to the payment in, in the field "Upon Receipt Use", select "In Transit Payment Account". See attached image
3. In the accounting configuration tab of the financial account, there must be 2 general ledger records and the "Cleared Payment Account" field must be empty in 2 general ledger records.
4. Posting the payment in will give a document disabled error.

https://github.com/etendosoftware/etendo_core/assets/143511686/6b8fa702-54e8-4d17-8e08-87e29e1ffd8c

# Expected behavior

It should give an error like the one in the attached image. Informing that there is no information in the field

# Affected Version

CORE: 23.4.1

# Solution Design (optional)

# Other test cases

  Given:

  When:

  Then:

**Comment by valeg-etendo** [comment]
Test

**Comment by juanfunes1996** [comment]
This task is closed as it is not reproduced in the latest current version 24.2.6.
