### ISSUE TITLE
[EPL-1414] Standard process definition add lines on a tab but you have to refresh to see them reflected

### ISSUE THREAD

**Issue by brunoromerosmf** [etendosoftware/etendo_core#343]
# Error's description
In a standard process definition, when new lines are added in relation to a header, the database is updated accordingly. However, to see these updates reflected on the interface, it is necessary to refresh the window. To be more precise, all the classes (processes) that extend BaseProcessActionHandler.

 # Steps to reproduce the error
The example is with the sales order window:
1. Create a sales order
2. Click in “Copy from orders” button
3. Select as many lines as you want.
4. Done

 # Expected behavior
It should not be necessary to refresh the window to see the new lines reflected.
 # Affected Version
¿ Latest/Specific ?

Starting from: 23.4.1

To: 24.1.1

# Solution design (optional)

Use as a solution concept the one applied by Matias in the issue attached below. 
https://github.com/etendosoftware/etendo_core/pull/337

# Other test cases
  Given: in sales order
  When: you run the buton of process "copy from orders" and select x number of lines
  Then: In the "lines" tab the selected lines should be loaded automatically without refreshing. 

 

  Given: in sales invoices
  When: you run the buton of process "create lines from order" and select x number of lines 
  Then: In the "lines" tab the selected lines should be loaded automatically without refreshing.

 

  Given: in sales invoices
  When: you run the buton of process "create lines from shipment" and select x number of lines 
  Then: In the "lines" tab the selected lines should be loaded automatically without refreshing.

 

  Given: in purchase order
  When: you run the buton of process "copy from orders" and select x number of lines 
  Then: In the "lines" tab the selected lines should be loaded automatically without refreshing.

 

  Given: in purchase order
  When: you run the buton of process "create lines" and select x number of lines
  Then: In the "lines" tab the selected lines should be loaded automatically without refreshing.

 

  Given: in purchase invoice 
  When: you run the buton of process "create lines from receipt" and select x number of lines
  Then: In the "lines" tab the selected lines should be loaded automatically without refreshing.

 

  Given: in purchase invoice
  When: you run the buton of process "create lines from order" and select x number of lines
  Then: In the "lines" tab the selected lines should be loaded automatically without refreshing.

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.1.1](https://github.com/etendosoftware/etendo_core/releases/tag/24.1.1).

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.1.2](https://github.com/etendosoftware/etendo_core/releases/tag/24.1.2).
