### ISSUE TITLE
ETP-51: Stock Valuation Report shows all records for an empty warehouse

### ISSUE THREAD

**Issue by juanfunes1996** [etendosoftware/etendo_core#351]
# Error's description
In the "Valued Stock Report" report, when you select a warehouse and it is empty, instead of the report coming out blank because there is no data, it shows all the records.

 # Steps to reproduce the error
1. Go to the Warehouses window and create a new warehouse and its corresponding empty spaces
2. This created store is linked to the organization.
3. The report is opened and filtered by that warehouse and that organization

 # Expected behavior
If there are no data in that warehouse and it is empty on that date, it should not show data in the report.

 # Affected Version
 ¿Latest/Specific?
Core Etendo version 23.4.5

 # Solution Design (optional)
![Reporte](https://github.com/etendosoftware/etendo_core/assets/143511686/d92db80d-ecf9-459a-8bb7-082d9200b1ba)
![Almacen AsociadoOrg](https://github.com/etendosoftware/etendo_core/assets/143511686/f3c88968-c5b5-43bc-af0c-1bc89efa956e)
![AlmacenNuevoVacio](https://github.com/etendosoftware/etendo_core/assets/143511686/bcaa76be-1a2b-4ea4-aabd-234cec97312d)
![FiltroReporte](https://github.com/etendosoftware/etendo_core/assets/143511686/0570b6f1-784f-4b06-a400-834830471f96)

 # Other test cases
 **Given:**
 **When:**
 **Then:**

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.2.8](https://github.com/etendosoftware/etendo_core/releases/tag/24.2.8) ⚡ 🚀
