### ISSUE TITLE
EPL-1435: Error messages do not show correctly when posting

### ISSUE THREAD

**Issue by RubenEtendo** [etendosoftware/etendo_core#358]
# Error's description
When trying to post a document, if the process throws an error, it will not be shown correctly. Instead of showing the correct cause of the message, the process returns an empty error message

 # Steps to reproduce the error
1. Login as admin on a new environment
2. Go to ‘Internal Consumption’ window
3. Create a new record and add a line to it (the specific information on what to put in is not relevant for this bug)
4. Process the Internal Consumption
5. Post the Internal Consumption
6. An empty error message will be shown
![image (7)](https://github.com/etendosoftware/etendo_core/assets/108277366/014f953f-77dd-4f39-a805-6eea88f74825)

 # Expected behavior
The message should explain that the table is not available for accounting

 # Affected Version
`Etendo Core -> 24.1.1`

 # Solution Design (optional)
* In the set_C_Period_ID method, before getting the period from the query result, add a null check to ensure no NullPointerException is thrown
```
if(data.length == 0) {
  C_Period_ID = "";
  return;
}
```

* In the setMessageResult process, instead of checking if the strMessage global variable is empty, check if it is not empty
```
if (StringUtils.isNotEmpty(strMessage)) {
  messageResult.setMessage(Utility.parseTranslation(conn, vars, params, vars.getLanguage(),
      Utility.parseTranslation(conn, vars, vars.getLanguage(), strMessage)));
}
```

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.1.2](https://github.com/etendosoftware/etendo_core/releases/tag/24.1.2).
