### ISSUE TITLE
ETP-59: Error in period when printing quotation

### ISSUE THREAD

**Issue by juanfunes1996** [etendosoftware/etendo_core#366]
# Error's description
The value displayed in the "Period" column is incorrect. It is incorrectly derived based on the period number in an organization's fiscal calendar.

 # Steps to reproduce the error

 ### Required Configurations (if necessary)

1 - Set up a new period for an organization. In this example, a record was created for December, but the period number does not match the month number in a standard calendar as it relates to a specific fiscal calendar of an organization.
![image](https://github.com/etendosoftware/etendo_core/assets/143511686/058c3d76-7f79-4aa7-abc4-9197f4eefe81)

2 - Navigate to the Budget window and create a new record. In the header, select the year of the previously created period and in the lines, specifically select the period.
![image](https://github.com/etendosoftware/etendo_core/assets/143511686/32c046dd-d726-485d-8a9f-8bb8123df323)

3 - Click on the "Export budget to excel" button
4 - View the "Period" column
![image](https://github.com/etendosoftware/etendo_core/assets/143511686/7596ebce-c02c-4e65-b1fd-023f53df05ba)

 # Expected behavior
The value in the "Period" column should be the period selected in the budget lines.

 # Affected Version
 ¿Latest/Specific?
 Version number:
Etendo Core: 24.1.2

 # Solution Design (optional)

 # Other test cases
 **Given:**
 **When:**
 **Then:**

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.3.1](https://github.com/etendosoftware/etendo_core/releases/tag/24.3.1) ⚡ 🚀
