### ISSUE TITLE
EPL-1450: The "ok" button is not locked when the dataset is already being applied.

### ISSUE THREAD

**Issue by brunoromerosmf** [etendosoftware/etendo_core#368]
# Error's description
When I select an organization and a dataset to install, and then click the "OK" button, the dataset installation process begins. However, the button is not deactivated, nor is there any message or visual indicator that the download is in progress. Due to the lack of visible changes on the screen, users may think that nothing is happening and click the button again, this can sometimes generate an error.

 # Steps to reproduce the error

1. Go to window "Enterprise module management"
2. Select an organization
3. Select an dataset (reference data)
4. Click in “ok“
5. Click again on the second click, you can try several clicks, you will be able to do this as the button does not lock and you will not see a change in the interface.

 ### Required Configurations (if necessary)
The dataset must have a large amount of data so that it takes a significant amount of time and you can click on it again.

 # Expected behavior
That the user can realize that the reference data application process is in progress.

 # Affected Version
 ¿Latest/Specific?
 Version number: Etendo core latest version (24.1.2)

 # Solution Design (optional)

 # Other test cases
 **Given:**
 **When:**
 **Then:**

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.1.5](https://github.com/etendosoftware/etendo_core/releases/tag/24.1.5).
