### ISSUE TITLE
ETP-58: Dataset creation for modules without "has reference data" checkbox marked is not blocked or notified

### ISSUE THREAD

**Issue by Amar-Etendo** [etendosoftware/etendo_core#371]
# Error's description

Creating a "Dataset" in Etendo for a specific module does not verify if the "has reference data" checkbox is marked in the module. This results in the dataset not being applicable once installed, as the dataset application window filters datasets belonging to modules with this checkbox marked.

# Steps to reproduce the error

Create a module and do not mark the "has reference data" checkbox.

Create a dataset for this module and export information into it.

Compile the system.

Attempt to apply the dataset.

The dataset will not be shown in the window.

# Expected behavior

The system should either prevent the creation of a dataset for modules without the "has reference data" checkbox marked, or notify the user that the dataset might not be applicable.

# Affected Version
Etendo Core -> 24.1.2

Actual version.

# Solution Design (optional)

Modify the module selector in the dataset creation window to only display modules that have the "has reference data" checkbox marked. This ensures that only applicable datasets are created. Its like the module selector and the "in development" checkbox in module related windows.

# Other test cases

Given: A module without "has reference data" marked.

When: A user attempts to create a dataset for this module.

Then: The system should either block the creation or notify the user that the dataset might not be applicable.

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.3.4](https://github.com/etendosoftware/etendo_core/releases/tag/24.3.4) ⚡ 🚀
