### ISSUE TITLE
ETP-60: Error when trying to post an “Internal Consumption” in Oracle

### ISSUE THREAD

**Issue by juanfunes1996** [etendosoftware/etendo_core#428]
# Error's description

In the Etendo core using Oracle as the database, in the "Internal Consumption" window, when trying to post the document even after running the costing process, the error is thrown: "The cost of the product @product@ has not been calculated."

# Steps to reproduce the error

**Go to the "Internal Consumption" window.**
Create a new record:
Name: testMovement
Data: <today>
Create a new line:
Product: Vino Tinto 0.75L
Movement Quantity: 1
Storage Bin: Rn-0-0-0
Click on "Process internal consumption".
**Go to “Document Type” Window**
Create a new record:Name: testPrint Name: testDocument Category: Material Internal Consumption
Save
**Go to “General Ledger Configuration” window**
Select “Active Tables” tab and set to active the “MaterialMgmtInternalConsumption” table.
**Go to the "Process request" window.**
Create a new record:
Organization: *
Process: Costing Background process
Timing: Run Immediately
Click on "Schedule Process".
**Go back to the "Internal Consumption" window and click on the "Post" button.**
The error "The cost of the product @product@ has not been calculated." will appear.

https://github.com/etendosoftware/etendo_core/assets/143511686/241680e7-17a6-46fe-8284-209cc833226a

# Expected behavior

The document should be posted without errors when executing the costing process.

# Affected Version 
Version number: 24.1.3

# Solution Design (optional)
Other test cases

Given: An insternal consumption is created
 When: The costing background process is executed.
 Then: Posting the document should not throw any error.

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.2.5](https://github.com/etendosoftware/etendo_core/releases/tag/24.2.5) 🚀
