### ISSUE TITLE
ETP-54: The report "Receivables Aging Schedule" doesn't show correct information in "doubtful debt" field when the report not shown details

### ISSUE THREAD

**Issue by Amar-Etendo** [etendosoftware/etendo_core#432]
# Error's description

The bug has been reproduced in demo, but we show a case in a customer.

Go to the "Receivables Aging Schedule" and select a customer with some invoices marked as “dobutful debt” in the window with that name.

If you show the report with the check “Show Details” marked, all goes fine. But if you show the report with the check “Show Details” unmarked, the report doesn’t show information for the field "doubtful debt".

# Steps to reproduce the error

## Required Configurations (if necessary)

As group admin role:
   Set the following accounts for 'Customer - Tier 1' Business Partner Category :
For F&B España, S.A. US/A/Euro GL:
  Doubtful Debt Account = 17000 - Deudas a largo plazo con entidades de crédito
  Bad Debt Expense Account = 17100 - Deudas a largo plazo
  Bad Debt Revenue Account = 17200 - Deudas a largo plazo transformables en subvenciones donaciones y legados
  Allowance For Doubtful Debt Account = 17900 - Deudas representadas en otros valores negociables

For F&B International Group US/A/US Dollar GL:
      Doubtful Debt Account = 7810 - Bad Debts Write-off
      Bad Debt Expense Account = 8020 - Bad Debt Expense
      Bad Debt Revenue Account = 4100 - Revenue - Product
      Allowance For Doubtful Debt Account = 4960 - Returns and Allowances

1. Create a Sales Invoice header for Alimentos y Supermercados, S.A bp.
2. Set its Invoice as Immediate.
3. Remove the discount in the Basic discounts tab.
4. Add a line, for instance:     
Product: Cerveza Ale 0,5L     
Quantity: 100    
Unit Price: 2.04     
Tax: Ventas exentas.   
5. Complete it.
6. Create a Doubtful Debt Run
7. Clear filters and select Doubtful Debt and select the previously created invoice
8. Process it 
9. Go to the "Receivables Aging Schedule" and select a business partner as  Alimentos y Supermercados, S.A
10. Select the flags Show Details and Show Doubtful Debt
11. Run the report as you will values in doubtful debt column/field
![image](https://github.com/etendosoftware/etendo_core/assets/165982236/9311c527-d0c9-462c-9161-0abe6370fd9f)

12. Uncheck the flag Show Details and run the report
13. There will zero value in doubtful debt column/field
![image](https://github.com/etendosoftware/etendo_core/assets/165982236/9152580e-f820-42fd-8faa-29d185c254e8)

# Expected behavior

So when select the flag Show Details as No and Show Doubt Debt as Yes, then also the report Receivables Aging Schedule must display the information/value for the doubtful debt column or field.

# Affected Version 

Version number: 24.1.7

# Solution Design (optional)

# Other test cases

  Given:

  When:

  Then:

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.2.8](https://github.com/etendosoftware/etendo_core/releases/tag/24.2.8) ⚡ 🚀
