### ISSUE TITLE
ETP-53: Wrong message text for message search key : REG_DESC

### ISSUE THREAD

**Issue by Amar-Etendo** [etendosoftware/etendo_core#440]
# Error's description 

Wrong message text for message search key : REG_DESC

# Steps to reproduce the error

1. Log in and change the role to System Administrator.
2. Enter the Message window.
3. Filter in the Search Key field by the key `REG_DESCRIPTION`
4. Open the record associated to this key and the message text content:
![image](https://github.com/etendosoftware/etendo_core/assets/165982236/9d78ba45-d01e-41ad-a815-eab3e0de4b6c)

# Expected behavior
Expected message text: **Registration description**

# Affected Version 
Version number: 24.3.x

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.3.3](https://github.com/etendosoftware/etendo_core/releases/tag/24.3.3) ⚡ 🚀
