### ISSUE TITLE
EPL-1703: Validation error in accounting processes . Existence of double negative in code.

### ISSUE THREAD

**Issue by juanfunes1996** [etendosoftware/etendo_core#442]
# Error's description
Validation error in accounting processes . Existence of double negative in code.

 # Steps to reproduce the error
AcctServerData.java code display . Existence of an incorrect double negative.
![image](https://github.com/user-attachments/assets/5158e2f2-215b-4908-ae99-72c0ce6ecdc2)

 # Expected behavior
The correct validation of conditions

 # Affected Version
Version number: Included in Etendo Core 24.1.1

 # Solution Design (optional)
Remove double negative to only verify that the object is not empty.

>[!IMPORTANT]
> The double negation introduced during the class refactor has been corrected. However, it is important to note that, according to our investigations, this code no longer executes because the "Process" tab in the "General Ledger Configuration" window is inactive in Etendo in this manner. This error was not detected by our automated tests because it concerns a deprecated functionality that we no longer support.

 # Other test cases
 **Given:** An accounting process configured and attached in "General ledger"
 **When:** The accounting process runs
 **Then:** The accounting process is executed

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.2.3](https://github.com/etendosoftware/etendo_core/releases/tag/24.2.3).
