### ISSUE TITLE
ETP-196: M_GET_STOCK_PARAM does not consider warehouse defined under organization window whether its active or not.

### ISSUE THREAD

**Issue by Amar-Etendo** [etendosoftware/etendo_core#455]
**Error's description**

The M_GET_STOCK_PARAM function does not consider the active status of warehouses defined under the Organization window when processing shipments. This results in shipments being created for inactive warehouses without any error or warning, which is incorrect behavior. The expected behavior is that the system should throw an error or display a warning when attempting to create a shipment for an inactive warehouse.

**Steps to reproduce the error**

1. Navigate to the Sales Order window.
2. Create a new Sales Order and select any business partner.
3. Add a product and specify the quantity.
4. Complete the Sales Order.
5. Navigate to the Organization window.
6. Select the relevant organization.
7. In the Warehouse tab, mark a warehouse as inactive.
8. Navigate to the Create Shipments from Orders window.
9. Select the Sales Order created in step 2.
10. Attempt to process the shipment
[ESD-696_Issue_Steps_Reproduced.webm](https://github.com/user-attachments/assets/f722ed3e-a73f-4a90-b14f-0d5bfde656a5)

**Required Configurations (if necessary)**

Ensure the warehouse associated with the organization is marked as inactive before processing the shipment.

**Expected behavior**

The system should throw an error or display a warning when attempting to create a shipment for an inactive warehouse, preventing the completion of the shipment process.

**Affected Version** 

¿ Latest/Specific ?

Version number: Latest/24.2.1

**Solution Design (optional)**

Modify the M_GET_STOCK_PARAM function to check the active status of the warehouse before allowing shipment creation. If the warehouse is inactive, an error or warning should be generated, and the shipment should not be processed.
Please refer the proposed solution patch provided by the partner.
[M_GET_STOCK_PARAM.txt](https://github.com/user-attachments/files/16597691/M_GET_STOCK_PARAM.txt)

Other test cases

  Given:

  When:

  Then:

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.2.7](https://github.com/etendosoftware/etendo_core/releases/tag/24.2.7) ⚡ 🚀
