### ISSUE TITLE
ETP-241: Error in Journal Entries Report, lines in some duplicate accounts

### ISSUE THREAD

**Issue by Amar-Etendo** [etendosoftware/etendo_core#461]
# Error's description
In the Journal Entry Report, several accounts are showing duplicate balances. This issue occurs when there is more than one clients / entity in the system.

# Steps to reproduce the error
Open an account, for example, "Captial Social" for the current date.
Ensure that this account in the organization tree has the translation carried out and that both in the current entity and the other entity have the same name and translation.
Execute the Journal Entries Report Advanced and Journal Entries Report.
Observe that the account balance is duplicated in the reports.
[ETP-241.webm](https://github.com/user-attachments/assets/ffe7b771-1ada-4c92-ab1f-f30c92aca0d9)
 

## Required Configurations (if necessary)

The system should have multiple entities with the same account name and translation in the organization tree.

# Expected behavior

The report should correctly filter the accounts at the time of the query by using the table "c_elementvalue" and filter by the entity "ad_client_id" to prevent duplicate balances from appearing.

# Affected Version 

**Version number**: Core Etendo - 24Q1.7

# Solution Design (optional)

The filtering should be enhanced when joining the account table. The current line:

`LEFT JOIN c_elementvalue ev ON F.ACCTDESCRIPTION = ev.name`

should be updated to:

`LEFT JOIN c_elementvalue ev ON (F.ACCTDESCRIPTION = ev.name and F.ACCTvalue = ev.value and F.AD_CLIENT_ID=ev.AD_CLIENT_ID and F.C_ACCTSCHEMA_ID = ev.c_element_id)`

# Other test cases

**Given**: A system with multiple entities with similar account names and translations.

**When**: The Journal Entries Report or Advanced Journal Entries Report is generated.

**Then**: The report should display the correct balance for each entity without duplication.

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.3.1](https://github.com/etendosoftware/etendo_core/releases/tag/24.3.1) ⚡ 🚀
