### ISSUE TITLE
ETP-377: Parsing Error with Scientific Notation

### ISSUE THREAD

**Issue by Amar-Etendo** [etendosoftware/etendo_core#481]
**Description**

**Error's description**
When performing a match statement in the Financial Account window and attempting to add a new transaction, entering a large deposit amount (e.g., 10000000.23) in the Deposit Amount field results in an incorrect value. Instead of showing the full deposit amount, the Actual Payment field displays 1.00.

**Steps to reproduce the error**

1. Navigate to the Financial Account window.
2. Perform a Match Statement.
3. Click on Add New Transaction.
4. In the Deposit Amount field, enter 10000000.23.
5. Press the Add button near the Payment field.
6. In the following section of the popup, observe that the Actual Payment field displays 1.00 instead of the entered deposit amount 10000000.23.
[ESD-741_Issue_Reproduced.webm](https://github.com/user-attachments/assets/a5eb5dcc-ec01-4b84-8090-1c896c73b0d7)

**Expected behavior**
After entering 10000000.23 in the Deposit Amount field and pressing Add, the Actual Payment field should correctly display 10000000.23.

**Affected Version** 
¿ Latest/Specific ?

Version number: Core version - 24.2.6

**Solution Design (optional)**
Other test cases
  Given:
  When:
  Then:

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.3.1](https://github.com/etendosoftware/etendo_core/releases/tag/24.3.1) ⚡ 🚀

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.3.1](https://github.com/etendosoftware/etendo_core/releases/tag/24.3.1) ⚡ 🚀
