### ISSUE TITLE
ETP-459: BaseActionHandler is not finished processing

### ISSUE THREAD

**Issue by brunoromerosmf** [etendosoftware/etendo_core#496]
# Error's description
When execute process that are BaseActionHandler, such as the SQL Expert synchronization or the Bulk Posting process, the execution never completes. This issue seems to be related to recent changes in the BaseActionHandler class, affecting the execution of these and potentially other processes. The processes remain in progress indefinitely, without generating any error logs.

 # Steps to reproduce the error

 ### Required Configurations (if necessary)
Install copilot.extensions 1.6.0 (latest) and financial.extensions 1.18.1 (latest) for examples

**Example 1**:
1. Access the assistant window.
2. Select any assistant, for example, SQL Expert.
3. Execute the synchronization process.

**Example 2**:
1. Go to sales invoices windows
2. Select two invoices unaccounted
3. Execute “bulk posting“

 # Expected behavior
The expected behavior is that these processes should function correctly and successfully.

 # Affected Version
 ¿Latest/Specific?
Latest
 Version number:
24.3.0

 # Solution Design (optional)
No specific solution proposed. Suggestions for reviewing recent changes to the baseActionHandler class. 

Notes:
What these processes have in common is that they have no parameters, the problem may come from that side.

 # Other test cases
 **Given:**
Recent changes in baseActionHandler 
 **When:**
Attempt to synchronize any assistant 
 **Then:**
The process should complete successfully without lingering in execution.

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.3.1](https://github.com/etendosoftware/etendo_core/releases/tag/24.3.1) ⚡ 🚀
