### ISSUE TITLE
ETP-619: Issue in the filtering of the Create Invoices from Orders window.

### ISSUE THREAD

**Issue by juanfunes1996** [etendosoftware/etendo_core#516]
# Error's description
The different column filters in the Create Invoices from Orders window do not apply correctly when the grid loads more data. In the first batch of data, the filters work correctly, but when more data is loaded, it loads as if no filters were applied, resulting in the display of undesired records. Additionally, in the same way, data that was previously selected is duplicated when more records are loaded.

 # Steps to reproduce the error

1. Navigate to the “Create Invoices from Orders” window.
2. Have/create enough orders to trigger an order load.
3. Filter by a column, such as Business Partner.
4. Select a record.
5. Trigger a second load of records.
6. Observe that the filters are not applied to this second load.

https://github.com/user-attachments/assets/2b30f3ca-5280-459a-9d46-6a7bbe20cdbd

# New case

**If there is more than one filter it seems to ignore the first one(s) taking into account only the last one.** 
1. Navigate to the “Create Invoices from Orders” window.
2. Filter by two or more columns, such as Business Partner and Organisations.
3. Select a record.
4. Trigger a second load of records.
5. Observe that the filters are not applied to this second load.

https://github.com/user-attachments/assets/ac054779-807d-48d7-9427-310ded2b562a

 # Expected behavior
Correct filtering after records load.

 # Affected Version
Etendo Core: 24.3.1

 # Solution Design (optional)

 # Other test cases
 **Given:**
 **When:**
 **Then:**

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.3.4](https://github.com/etendosoftware/etendo_core/releases/tag/24.3.4) ⚡ 🚀

**Comment by valeg-etendo** [comment]
> [!IMPORTANT]
> Bug resolved in version [24.3.6](https://github.com/etendosoftware/etendo_core/releases/tag/24.3.6) ⚡ 🚀
