### ISSUE TITLE
EPL-439 Error when executing a compile.complete in Windows

### ISSUE THREAD

**Issue by demian-romero** [etendosoftware/etendo_core#96]
**Error's description**
The following error is displayed when executing a compile.complete on Windows:

[Build Scan™ | Gradle Cloud Services](https://scans.gradle.com/s/hihup5r5hzm5a/failure)

**Steps to reproduce the error**
Test performed on a Windows 10, simply the error occurs when executing compile.complete. Attached is a screenshot of the error in the test performed.
![compilecomplete_error](https://user-images.githubusercontent.com/110682447/195662067-55e63a4c-2653-4399-a6db-b9a1eddbdfff.jpeg)

**Expected behavior**
That the execution of compile.complete ends correctly.

**Affected Version**
Etendo 22Q1.3

**Comment by valeg-etendo** [comment]
This issue was resolved in the following Pull Request: https://github.com/etendosoftware/com.etendoerp.gradleplugin/pull/5

**Comment by valeg-etendo** [comment]
This issue was resolved in the following Pull Request: https://github.com/etendosoftware/com.etendoerp.gradleplugin/pull/5
