### ISSUE TITLE
EPL-456 Error in first time execution of an scheduled process

### ISSUE THREAD

**Issue by demian-romero** [etendosoftware/etendo_core#98]
**Steps to reproduce the error** 
When you create a new scheduled process of some process (e.g Acct Server Process) with timing as "Schedule" option and a frequency, the first execution finish with status "Misfired" without process log.

**Expected behavior** 
That this first execution has the same way of behaving as the following executions 

**Affected Version** 
Etendo 22Q3

![image-20221109-134219](https://user-images.githubusercontent.com/110682447/200867493-22e5e570-6c15-4621-943f-5b8b288b76bf.png)
![image-20221109-134211](https://user-images.githubusercontent.com/110682447/200867509-c6f3e3f4-9f1b-453f-98e3-3ff8901afc49.png)
![image-20221109-134158](https://user-images.githubusercontent.com/110682447/200867518-2f4c129e-8111-4563-bc18-de35aaac0344.png)

**Comment by sebastianbarrozo** [comment]
Is a quartz expected behavior, please refer to:
https://nurkiewicz.com/2012/04/quartz-scheduler-misfire-instructions.html
https://dzone.com/articles/quartz-scheduler-misfire
http://www.quartz-scheduler.org/documentation/2.4.0-SNAPSHOT/configuration.html

This won't be fixed.
